subestacao:

  dataset: /home/ale/Downloads/ale/dataset
  weights: 
  confidence: 0.1
  label: subestacao
  epochs: 50
  device: cpu
  result_folder_name: run_300_epochs
  model: yolo11n.pt
  train: true
  detect: false
