subestacao:
<<<<<<< HEAD
 
  dataset: /home/ale/datasets/subestacao
  weights: /home/ale/datasets/subestacao/runs/run_500_epochs/weights/best.pt
  confidence: 0.1
  label: subestacao
  epochs: 500
  device: 0
  result_folder_name: run_500_epochs
  model: yolo11n.pt
  train: true
  detect: false
  annotate: true
  annotate_confidence: 0.1 
  labels_to_annotate:  
    ['disjuntor',
    'painel_eletrico',
    'seccionadora',
    'canaleta',
    'poste',
    'reator_de_barra',
    'transformador_de_corrente',
    'transformador_de_potencial',
    'isolador_pedestal',
    'barra'
    ]
  
=======

  dataset: /home/ale/Downloads/ale/dataset
  weights: 
  confidence: 0.1
  label: subestacao
  epochs: 50
  device: cpu
  result_folder_name: run_300_epochs
  model: yolo11n.pt
  train: true
  detect: false
>>>>>>> 260c9fd82e0819769cd3c907fa36943028156b32
