sample_object:

  dataset: /path_to_object/dataset
  weights: /path_to_object/dataset/runs/run_300_epochs/weights/best.pt
  confidence: 0.1
  label: sample_object
  epochs: 300
  device: cpu
  result_folder_name: run_300_epochs
  model: yolo11n.pt
  train: false
  detect: true


sample_object_segmentation:

  dataset: /path_to_object_seg/dataset/sample_object_segmentation
  weights: /path_to_object_seg/dataset/sample_object_segmentation/runs/run_300_epochs/weights/best.pt
  confidence: 0.5
  label: sample_object_segmentation
  epochs: 300
  device: cpu
  result_folder_name: run_300_epochs
  model: yolo11n-seg.pt
  train: false
  detect: false
  segmentation: true

